sudo: required

cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "stable"

branches:
  only:
    - deploy-storybook

#env:
#  - NODE_RELEASE=12.x

# Ajouter le domaine au ficher known host de la machine virtuelle
addons:
  ssh_known_hosts:
    - libraries.willybrauner.com

# config SSH
before_install:
  - echo -e "Host ${DEPLOY_URL}ntStrictHostKeyChecking non" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_d6991b43c6df_key -iv $encrypted_d6991b43c6df_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - sudo chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  # installer node
  #- curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}"
  #- sudo apt-get install -y nodejs
  #- npm install -g npm@4
  #- npm --version
  # aller dans le dossier
  - cd packages/storybook
  # show repertory
  - ls
  # installer des dépendances front
  - npm ci

script:
  - ls
  # builder les sources
  #- npm run build-storybook
  # pousser les sources sur le serveur distant
  - rsync --checksum --recursive --archive --delete --rsh "ssh -o StrictHostKeyChecking=no" packages/storybook/storybook-static ${SSH_USER}@${DEPLOY_URL}:${DEPLOY_FOLDER}
